# Generated by Django 4.1.9 on 2024-01-25 03:33

from typing import List, Tuple
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: List[Tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="KeyringItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expiry", models.DateTimeField()),
                ("key", models.CharField(max_length=512)),
                ("url", models.URLField()),
            ],
            options={
                "ordering": ["url"],
            },
        ),
        migrations.AddIndex(
            model_name="keyringitem",
            index=models.Index(fields=["expiry"], name="wagtailcach_expiry_b9702b_idx"),
        ),
        migrations.AddIndex(
            model_name="keyringitem",
            index=models.Index(fields=["key"], name="wagtailcach_key_0c2934_idx"),
        ),
        migrations.AddIndex(
            model_name="keyringitem",
            index=models.Index(fields=["url"], name="wagtailcach_url_04699f_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="keyringitem",
            unique_together={("url", "key")},
        ),
    ]
