# Generated by Django 4.2.15 on 2024-10-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcache", "0002_increase_url_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyringitem",
            name="url",
            field=models.TextField(),
        ),
    ]
